config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # api
  post '/api/v3/projects/:project_id/notices'     => 'airbrake_notice#notices'
  post '/api/v3/projects/:project_id/ios-reports' => 'airbrake_report#ios_reports'

  # settings
  resources :projects do
    member do
      post 'airbrake_settings' => 'airbrake_project_settings#update'
    end
  end
end

app/views/projects/settings/_airbrake.html.erb
<% @airbrake_project_setting ||= (@project.airbrake_settings || AirbrakeProjectSetting.new(project: @project)) %>

<%= error_messages_for 'airbrake_project_setting' %>

<h2><%= l(:label_airbrake) %></h2>

<%= labelled_form_for :airbrake_project_setting, @airbrake_project_setting, url: airbrake_settings_project_path(@project), html: {method: :post, id: 'airbrake-form'} do |f| %>
  <%= error_messages_for 'airbrake_project_setting' %>

  <div class="box tabular">
    <p>
      <%=f.select :tracker_id, options_from_collection_for_select(@project.trackers, :id, :name, @airbrake_project_setting.tracker_id), include_blank: true %>
    </p>
    <p>
      <%=f.select :category_id, options_from_collection_for_select(@project.issue_categories, :id, :name, @airbrake_project_setting.category_id), include_blank: true %>
    </p>
    <p>
      <%=f.select :priority_id, options_from_collection_for_select(IssuePriority.order(:position), :id, :name, @airbrake_project_setting.priority_id), include_blank: true %>
    </p>
    <p>
      <%=f.text_field :reopen_regexp %>
      <em class="info">(<%=l(:text_regexp_info)%>)</em>
    </p>
    <p>
      <%=f.check_box :reopen_repeat_description %>
    </p>
  </div>

  <p>
    <%= submit_tag(l(:button_save)) %>
  </p>
<% end %>